# Generated by Django 3.0.8 on 2020-09-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(max_length=500)),
                ('price', models.IntegerField()),
                ('image', models.CharField(max_length=256)),
                ('category', models.CharField(max_length=64)),
            ],
        ),
    ]
