# Generated by Django 3.0.8 on 2020-09-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200926_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bidder',
            field=models.CharField(max_length=64),
        ),
    ]
